### ISSUE TITLE
window functions 

### ISSUE THREAD

**Issue by priyank-panchal** [AmmarAbdelhalem/FSM#2]
would like to request the addition of a **Windows function** in the FSM.

**Comment by AmmarAbdelhalem** [comment]
Sorry I can't understand your meaning, what do you mean by addition of a windows function in FSM?

**Comment by priyank-panchal** [comment]
Please add the notes on the Windows function.

**Comment by AmmarAbdelhalem** [comment]
Sorry for misunderstanding, I actually work in a new release for the notes I will add **Windows Functions** in my list, thanks for contribute.
